name: Android CI
on:
  workflow_dispatch: # 手动触发
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: set up JDK 
      uses: actions/setup-java@v5
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
 #     run: ./gradlew build
      run: ./gradlew assembleDebug 
    - uses: actions/upload-artifact@v4
      with:
        name: trtoolbox
        path: '**/*.apk'
